### ISSUE TITLE
UnicodeEncodeError when outputing not-ascii characters

### ISSUE THREAD

**Issue by leopd** [aws/sagemaker-containers#159]
What is the recommended way to output non-ascii characters?

This minimal example fails with `UnicodeEncodeError`

```
#!/usr/bin/env python

print(u"\u2639")  # print sad face
```

specifically, when running with PyTorch in local mode, this is the full stack trace:

```
algo-1-3lmzz_1  | Invoking script with the following command:
algo-1-3lmzz_1  | 
algo-1-3lmzz_1  | /usr/bin/python -m unicode_test
algo-1-3lmzz_1  | 
algo-1-3lmzz_1  | 
algo-1-3lmzz_1  | 2019-01-07 19:38:45,883 sagemaker-containers ERROR    ExecuteUserScriptError:
algo-1-3lmzz_1  | Command "/usr/bin/python -m unicode_test"
algo-1-3lmzz_1  | Traceback (most recent call last):
algo-1-3lmzz_1  |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
algo-1-3lmzz_1  |     "__main__", mod_spec)
algo-1-3lmzz_1  |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
algo-1-3lmzz_1  |     exec(code, run_globals)
algo-1-3lmzz_1  |   File "/opt/ml/code/unicode_test.py", line 3, in <module>
algo-1-3lmzz_1  |     print(u"\u2639")  # print sad face
algo-1-3lmzz_1  | UnicodeEncodeError: 'ascii' codec can't encode character '\u2639' in position 0: ordinal not in range(128)
tmpdl15aqf5_algo-1-3lmzz_1 exited with code 1
Aborting on container exit...
```

executed by:

```
sagemaker.pytorch.PyTorch(
    entry_point='unicode_test.py',
    train_instance_type='local',
    train_instance_count=1,
    framework_version='1.0.0',
 ).fit()
```

I've tried a bunch of things like changing environment variables to set locale, but the only thing that I've gotten to work is to encode in ascii, which is not a good solution.

**Comment by nadiaya** [comment]
Please, try using the newest PyTorch container - we released an unrelated change today that also should address this issue.

Keeping open + adding bug label since this issue most likely is present in other containers as well.

**Comment by yangaws** [comment]
Hi @leopd ,

As Nadia said, latest PyTorch container does not have this problem in Py3. And the codes to fix that in Py2 are already merged. So now there should not be any utf-8 related errors in PyTorch container.

And there are such errors in other framework containers @nadiaya . But I feel it's not a good way to track them in this issue under Pytorch repo. I will close this issue and track them elsewhere.

Please reopen if you have further questions.
