### ISSUE TITLE
How to emit serving metrics?

### ISSUE THREAD

**Issue by ChoiByungWook** [aws/sagemaker-containers#178]
There doesn't seem to be any ability to emit serving metrics of any kind in this repository.

There is no way to get metrics in regards to model latency, predict time, inference time or anything related to the GUnicorn workers.

There seems to be an env for enabling metrics: https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_params.py#L24.

It looks like in container_support, there was some support for metrics using telegraf: https://github.com/aws/sagemaker-containers/blob/r1.0/src/container_support/serving.py#L79

However, in sagemaker-containers, I can't seem to find anything.

**Comment by mvsusp** [comment]
Hello @ChoiByungWook,

The feature to emit serving metrics via telegraf was discontinued after the endpoint monitor was released:

![screen shot 2019-02-25 at 10 53 09 am](https://user-images.githubusercontent.com/142074/53360990-db58a300-38eb-11e9-89b8-f088b8bb6eb8.png)

The monitor captures invocation and instance metrics without consuming endpoint resources. More specifically about GUnicorn workers, I don't remember any specific metric for it.

I will close this ticket, please let me know if you have more questions!

Thanks for using SageMaker.
