### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by david-waterworth** [aws/sagemaker-containers#195]
I'm working my way through migrating a container to use sagemaker-containers, I've found a minor documentation issue, and I have a few suggestions / observations.

[README.rst](https://github.com/aws/sagemaker-containers#id7) states 

> The training script must be located under the folder /opt/ml/model and its relative path is defined in the environment variable SAGEMAKER_PROGRAM

But the Dockerfile copies the file to  `/opt/ml/code` not `/opt/ml/model`. I suspect the documentation is wrong?

Also it took me a while to figure out ENV is used by `sagemaker-containers` to location the `train` endpoint. i.e.

ENV SAGEMAKER_PROGRAM train.py

I think this could be more explicit, i.e. list all the ENV options and how they're invoked, I've found `SAGEMAKER_PROGRAM` and `SAGEMAKER_TRAINING_MODULE` which I assume are for scripts and a callable (which seems to take zero args?)

Finally I've not yet looked at the `serve` endpoint yet but I don't see much in the way of details on how that works i.e. to the level of [TRAINING_IN_DETAIL.rst](https://github.com/aws/sagemaker-containers/blob/6ae9cb4aba35fc7c9c05739bc72b367399267871/TRAINING_IN_DETAIL.rst)

And it would be really nice if 'local' worked without having to setup credentials, and pass an arn to role=''  (ideally `docker run -v \opt\ml:\opt\ml XYZ train` would work provided \opt\ml has the required structure)

**Comment by ChoiByungWook** [comment]
Hello @david-waterworth,

Thank you so much for bringing this documentation issue to our attention.

We will make sure to update the README to reflect the correct information.

Thank you for the suggestions as well in regards to the local and the serving documentation.
