### ISSUE TITLE
Where did entry.py went?

### ISSUE THREAD

**Issue by elgalu** [aws/sagemaker-containers#197]
Works:
https://github.com/aws/sagemaker-containers/blob/049a8346a1de85c51dea153c1d81bc788af0cf34/bin/entry.py

Gone:
https://github.com/aws/sagemaker-containers/blob/master/bin/entry.py

**Comment by laurenyu** [comment]
hi @elgalu,

v2 of SageMaker Containers featured a complete overhaul of the code, so there were a lot of major changes, including the removal of `entry.py`.

The entry points are now defined here:
