### ISSUE TITLE
wrong env var name in README

### ISSUE THREAD

**Issue by Henriii** [aws/sagemaker-containers#205]
Under "List of provided environment variables by SageMaker Containers"

**a)**
The code example for **SM_INPUT_CONFIG_DIR** seems to be wrong, it says
`SM_INPUT_DIR=/opt/ml/input/config`
instead of 
`SM_INPUT_CONFIG_DIR=/opt/ml/input/config`

**b)**
The first sentence of the explanation text reads:

 > The path of the input directory, e.g. /opt/ml/input/config/. 

I guess this is also a copy&paste error and should instead read: 

> The path of the input configuration directory, e.g. /opt/ml/input/config/.

**Comment by ChoiByungWook** [comment]
@Henriii,

Thanks for bringing this to our attention.

Let me add a PR to fix this right away.
