### ISSUE TITLE
Is there any way to open SSH port for sagemaker containers, so I can remote log in from local machine?

### ISSUE THREAD

**Issue by phamquiluan** [aws/sagemaker-containers#256]

**Comment by laurenyu** [comment]
@phamquiluan sorry for the lack of response here

for clarification, are you asking to ssh into a training instance or endpoint?

**Comment by phamquiluan** [comment]
@laurenyu I mean the training instance. 

Besides, just my curiosity, what is the endpoint you mention about?

**Comment by laurenyu** [comment]
this is what I meant by "endpoint": https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-hosting.html

I don't believe it's possible to SSH into a training instance, but I'm going to pass this along to the SageMaker Training team so that they can confirm.
