### ISSUE TITLE
This package does not have any documentation?

### ISSUE THREAD

**Issue by derekhh** [aws/sagemaker-containers#26]
I've only noticed this package while reading the source code for https://github.com/aws/sagemaker-tensorflow-containers/blob/b0deecd2745391c65048e3d72bb0c008b2feef55/src/tf_container/train.py#L18. It seems to me that this package could make a lot of things convenient but it seems there is no documentation or announcement from SageMaker on this package. Why is that?

**Comment by lukmis** [comment]
Thanks derekhh. I believe the announcement covered open-sourcing of the containers and this repo is used by them as it holds common code/functionality.
We will update documentation.

**Comment by yangaws** [comment]
Hi @derekhh ,

Now we have our first version of README. We will keep working to make it better and your feedbacks are welcome!

Thanks

**Comment by laurenyu** [comment]
closing this issue as there is a README now. as Yang mentioned, feel free to open issues or PRs if you have any suggestions for improving the documentation
