### ISSUE TITLE
Shell command arguments need to be quoted

### ISSUE THREAD

**Issue by vgod-dbx** [aws/sagemaker-containers#263]
We ran into a problem that the training scripts failed to execute when user specified arguments have special characters (e.g. spaces or parentheses). I dug into the code a bit and found out the arguments were not quoted properly when the command was constructed. The offensive code is at https://github.com/aws/sagemaker-containers/blob/40852529146497535b25ca02c54376e87f92cd97/src/sagemaker_containers/_process.py#L139

**Comment by laurenyu** [comment]
thanks for the bug report! I've opened a PR to fix this: https://github.com/aws/sagemaker-containers/pull/265

**Comment by vgod-dbx** [comment]
Awesome! Thanks for the quick fix!

**Comment by laurenyu** [comment]
fix was released in [v2.8.3](https://github.com/aws/sagemaker-containers/releases/tag/v2.8.3).

@vgod-dbx is there a specific pre-built image you need this released in?

**Comment by vgod-dbx** [comment]
Great. Thanks!
We are using Sagemaker's Tensorflow 1.12.0 + Python 2 pre-built image. Isn't this going to be released in all Sagemaker's pre-built images? We may want to upgrade to a newer version of Tensorflow later, so just want to make sure this will be fixed in all versions.

**Comment by laurenyu** [comment]
we typically release fixes to only the latest images. are you able to upgrade to TF 1.15 (or TF 2.1)?

**Comment by vgod-dbx** [comment]
Unfortunately, not at this moment. :(
We are working on upgrading to TF 2.1, but it'll take a few months. So, in
the meantime, we still need to use TF 1.12 for a while.

**Comment by laurenyu** [comment]
we'll see what we can do to release TF 1.12, but unfortunately it may take awhile 😞 

in the meantime, you can build the TF 1.12 image on your own with a Dockerfile that looks like:

```dockerfile
FROM 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12.0-cpu-py2
RUN pip install --upgrade sagemaker-containers==2.8.3
```

For `520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12.0-cpu-py2`, you should modify the region, "-scriptmode" suffix, and processor (i.e. cpu vs gpu) as appropriate

**Comment by vgod-dbx** [comment]
@laurenyu any updates on releasing this fix to the official images? We have switched to TF 1.14 now. Just curious when the fix will be available.
