### ISSUE TITLE
A/B testing?

### ISSUE THREAD

**Issue by mlaicode** [aws/sagemaker-containers#85]
I am unable to find how these containers can be enabled for A/B testing? Is this feature in here? 
The docs says "Amazon SageMaker also includes built-in A/B testing capabilities to help you test your model and experiment with different versions to achieve the best results."

Also, any comments on best practices for managing different production model variants? How are your customers using this model variants feature?

**Comment by yangaws** [comment]
Hi @mlaicode ,

The way you do A/B testing is not related to this repo. You may want to use AWS SDK for it.

Basically you could refer to this page (https://docs.aws.amazon.com/sagemaker/latest/dg/API_ProductionVariant.html) and create ``ProductionVariant`` with specifying ``InitialVariantWeight`` to control the traffic. And you could refer to this page (https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateEndpointConfig.html) to create an ``EndpointConfig`` with the ``ProductionVariants`` you have for A/B testing.

We currently don't have a good code example for doing this. I will mark this issue as a feature request for us to add an example.

Thanks for using SageMaker!
